name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Update pip
        run:
          python -m pip install --upgrade pip

      - name: Install dependencies
        run:
          pip install -r requirements.dev.txt

      - name: Run mypy
        run: mypy --cache-dir=/dev/null --explicit-package-bases --check-untyped-defs .

      - name: Run pytest
        run: pytest

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
